// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3oz_v9qzqomlIRvXb2NNdQIUNEd4Erm8',
    appId: '1:536946297105:web:83bcc9c48e91bd42bb24b0',
    messagingSenderId: '536946297105',
    projectId: 'sightway-9f360',
    authDomain: 'sightway-9f360.firebaseapp.com',
    databaseURL: 'https://sightway-9f360-default-rtdb.firebaseio.com',
    storageBucket: 'sightway-9f360.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnFafqSm_BX0cwamYVOWLMnfXOhY_m32I',
    appId: '1:536946297105:android:f5674865031e5121bb24b0',
    messagingSenderId: '536946297105',
    projectId: 'sightway-9f360',
    databaseURL: 'https://sightway-9f360-default-rtdb.firebaseio.com',
    storageBucket: 'sightway-9f360.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCON-HjL3soX4iTD6aqkgCRz9l-0aA5rLQ',
    appId: '1:536946297105:ios:d980e835a09236b8bb24b0',
    messagingSenderId: '536946297105',
    projectId: 'sightway-9f360',
    databaseURL: 'https://sightway-9f360-default-rtdb.firebaseio.com',
    storageBucket: 'sightway-9f360.firebasestorage.app',
    iosBundleId: 'com.example.sightwayMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCON-HjL3soX4iTD6aqkgCRz9l-0aA5rLQ',
    appId: '1:536946297105:ios:d980e835a09236b8bb24b0',
    messagingSenderId: '536946297105',
    projectId: 'sightway-9f360',
    databaseURL: 'https://sightway-9f360-default-rtdb.firebaseio.com',
    storageBucket: 'sightway-9f360.firebasestorage.app',
    iosBundleId: 'com.example.sightwayMobile',
  );
}
